schema_version: '2.0'
title: Hoffman2018- ADCC against cancer Lab
description: 'The paper describes a model of ADCC. Created by COPASI 4.26 (Build 213)
  This model is described in the article: A mathematical model of antibody-dependent
  cellular cytotoxicity (ADCC) F.'
models:
- alias: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.state
  to:
  - visualisation.immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model_state
- from: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.summary
  to:
  - visualisation.immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model_summary
- from: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.species_labels
  to:
  - visualisation.immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `A`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `R`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 1.0
    units: substance
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `S`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `C`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.state
  - name: summary
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.summary
  - name: species_labels
    maps_to: immunology_sbml_hoffman2018_adcc_against_cancer_biomd0000000802_model.species_labels
