schema_version: '2.0'
title: Jarrett2018 - trastuzumab-induced immune response in murine HER2+ breast cancer
  model Lab
description: 'The paper describes a model on the trastuzumab-induced immune response
  in murine(mouse) HER2+ breast cancer.Created by COPASI 4.25 (Build 207) This model
  is described in the article: Mathematical mode. It can be used to explore immune
  response dynamics and compare pathway-level behavior across conditions.'
models:
- alias: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.state
  to:
  - visualisation.immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model_state
- from: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.summary
  to:
  - visualisation.immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model_summary
- from: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.species_labels
  to:
  - visualisation.immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 0.2
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `T`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.071
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `I`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 0.12
    units: substance
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `V`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.1
    units: substance
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `N`.
  - name: initial_unresolved_tumor_observable_5
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.initial_unresolved_tumor_observable_5
    label: Initial Unresolved Tumor Observable 5
    default: 0.18
    units: substance
    description: Initial Unresolved Tumor Observable 5. Sets the initial value of
      bundled SBML species `H`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.unresolved_tumor_observable_4
  - name: unresolved_tumor_observable_5
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.unresolved_tumor_observable_5
  - name: state
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.state
  - name: summary
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.summary
  - name: species_labels
    maps_to: immunology_sbml_jarrett2018_trastuzumab_induced_immune_response_biomd0000000745_model.species_labels
