schema_version: '2.0'
title: Vibert2017 - Tcell proliferation model Lab
description: model allows us to infer proliferation rates and cell cycle phase durations
  from complex experimental 5-ethynyl-2'-deoxyuridine (EdU) data, revealing T cell
  proliferation heterogeneity and specific si. It can be used to explore immune response
  dynamics and compare pathway-level behavior across conditions.
models:
- alias: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.state
  to:
  - visualisation.immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model_state
- from: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.summary
  to:
  - visualisation.immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model_summary
- from: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.species_labels
  to:
  - visualisation.immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_immune_observable_1
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.initial_unresolved_immune_observable_1
    label: Initial Unresolved Immune Observable 1
    default: 12.0
    units: native source value
    description: Initial Unresolved Immune Observable 1. Sets the initial value of
      bundled SBML species `M`.
  - name: initial_unresolved_immune_observable_2
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.initial_unresolved_immune_observable_2
    label: Initial Unresolved Immune Observable 2
    default: 0.0
    units: native source value
    description: Initial Unresolved Immune Observable 2. Sets the initial value of
      bundled SBML species `M_p`.
  - name: initial_unresolved_immune_observable_3
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.initial_unresolved_immune_observable_3
    label: Initial Unresolved Immune Observable 3
    default: 4.88455
    units: native source value
    description: Initial Unresolved Immune Observable 3. Sets the initial value of
      bundled SBML species `G`.
  - name: initial_unresolved_immune_observable_4
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.initial_unresolved_immune_observable_4
    label: Initial Unresolved Immune Observable 4
    default: 88.8988
    units: native source value
    description: Initial Unresolved Immune Observable 4. Sets the initial value of
      bundled SBML species `S`.
  - name: initial_unresolved_immune_observable_5
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.initial_unresolved_immune_observable_5
    label: Initial Unresolved Immune Observable 5
    default: 0.0
    units: native source value
    description: Initial Unresolved Immune Observable 5. Sets the initial value of
      bundled SBML species `G_p`.
  outputs:
  - name: unresolved_immune_observable_1
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.unresolved_immune_observable_1
  - name: unresolved_immune_observable_2
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.unresolved_immune_observable_2
  - name: unresolved_immune_observable_3
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.unresolved_immune_observable_3
  - name: unresolved_immune_observable_4
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.unresolved_immune_observable_4
  - name: unresolved_immune_observable_5
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.unresolved_immune_observable_5
  - name: state
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.state
  - name: summary
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.summary
  - name: species_labels
    maps_to: immunology_sbml_vibert2017_tcell_proliferation_model_model2003170002_model.species_labels
