schema_version: '2.0'
title: Eftimie2017/1 - interaction of Th and macrophage Lab
description: 'The paper describes a model of interaction of Th cells and macrophage
  in melanoma. Created by COPASI 4.25 (Build 207) This model is described in the article:
  Modelling and investigation of the CD4 T c.'
models:
- alias: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.state
  to:
  - visualisation.immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model_state
- from: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.summary
  to:
  - visualisation.immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model_summary
- from: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.species_labels
  to:
  - visualisation.immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `H1`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `H2`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 100.0
    units: substance
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `M1`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `M2`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.state
  - name: summary
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.summary
  - name: species_labels
    maps_to: immunology_sbml_eftimie2017_1_interaction_of_th_and_macrophage_biomd0000000770_model.species_labels
