schema_version: '2.0'
title: Frank2021 - Macrophage polarization Lab
description: The model describes the mechanisms by which macrophages differentiate
  into a given phenotype. The model shows that both extracellular and intracellular
  signalling are both important for that process.
models:
- alias: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.state
  to:
  - visualisation.immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model_state
- from: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.summary
  to:
  - visualisation.immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model_summary
- from: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.species_labels
  to:
  - visualisation.immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_signaling_observable_1
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.initial_unresolved_signaling_observable_1
    label: Initial Unresolved Signaling Observable 1
    default: 1.2
    units: native source value
    description: Initial Unresolved Signaling Observable 1. Sets the initial value
      of bundled SBML species `x1`.
  - name: initial_unresolved_signaling_observable_2
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.initial_unresolved_signaling_observable_2
    label: Initial Unresolved Signaling Observable 2
    default: 2.0
    units: native source value
    description: Initial Unresolved Signaling Observable 2. Sets the initial value
      of bundled SBML species `x2`.
  outputs:
  - name: unresolved_signaling_observable_1
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.unresolved_signaling_observable_1
  - name: unresolved_signaling_observable_2
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.unresolved_signaling_observable_2
  - name: state
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.state
  - name: summary
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.summary
  - name: species_labels
    maps_to: immunology_sbml_frank2021_macrophage_polarization_biomd0000001060_model.species_labels
