schema_version: '2.0'
title: Wilkie2013b - immune-induced cancer dormancy and immune evasion-basic Lab
description: 'The paper describes a basic model of immune-induced cancer dormancy
  and immune evasion. Created by COPASI 4.25 (Build 207) This model is described in
  the article: Mathematical models of immune-induced.'
models:
- alias: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.state
  to:
  - visualisation.immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model_state
- from: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.summary
  to:
  - visualisation.immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model_summary
- from: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.species_labels
  to:
  - visualisation.immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `C`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 100.0
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `I`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.unresolved_tumor_observable_2
  - name: state
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.state
  - name: summary
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.summary
  - name: species_labels
    maps_to: immunology_sbml_wilkie2013b_immune_induced_cancer_dormancy_and_i_biomd0000000751_model.species_labels
