schema_version: '2.0'
title: Maier2022 - Stochastic Dynamics of Type I Interferon Responses Lab
description: Maier2022 - Stochastic Dynamics of Type I Interferon ResponsesOur study
  aims to determine whether and how biochemical noise affects the information transduced
  in the JAK-STAT signaling pathway and inv. It can be used to explore immune response
  dynamics and compare pathway-level behavior across conditions.
models:
- alias: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.state
  to:
  - visualisation.immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model_state
- from: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.summary
  to:
  - visualisation.immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model_summary
- from: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.species_labels
  to:
  - visualisation.immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_cytosolic_stat2_irf9_complex
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.initial_cytosolic_stat2_irf9_complex
    label: Initial Cytosolic Stat2 Irf9 Complex
    default: 231.21387283237
    units: native source value
    description: Initial Cytosolic Stat2 Irf9 Complex. Sets the initial value of bundled
      SBML species `STAT2_IRF9_c`.
  - name: initial_nuclear_stat2_irf9_complex
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.initial_nuclear_stat2_irf9_complex
    label: Initial Nuclear Stat2 Irf9 Complex
    default: 2407.40740740741
    units: native source value
    description: Initial Nuclear Stat2 Irf9 Complex. Sets the initial value of bundled
      SBML species `STAT2_IRF9_n`.
  - name: initial_interferon
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.initial_interferon
    label: Initial Interferon
    default: 11560.6936416185
    units: native source value
    description: Initial Interferon. Sets the initial value of bundled SBML species
      `IFN`.
  - name: initial_cytosolic_stat1
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.initial_cytosolic_stat1
    label: Initial Cytosolic Stat1
    default: 983430.057803468
    units: native source value
    description: Initial Cytosolic Stat1. Sets the initial value of bundled SBML species
      `STAT1_c`.
  - name: initial_pstat1
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.initial_pstat1
    label: Initial Pstat1
    default: 0.0
    units: native source value
    description: Initial Pstat1. Sets the initial value of bundled SBML species `pSTAT1`.
  outputs:
  - name: cytosolic_stat2_irf9_complex
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.cytosolic_stat2_irf9_complex
  - name: nuclear_stat2_irf9_complex
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.nuclear_stat2_irf9_complex
  - name: interferon
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.interferon
  - name: cytosolic_stat1
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.cytosolic_stat1
  - name: pstat1
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.pstat1
  - name: state
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.state
  - name: summary
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.summary
  - name: species_labels
    maps_to: immunology_sbml_maier2022_stochastic_dynamics_of_type_i_interfer_model2210070001_model.species_labels
