schema_version: '2.0'
title: dePillis2007 - Chemotherapy for tumors An analysis of the dynamics and a study
  of quadratic and linear optimal controls Lab
description: "AbstractWe investigate a mathematical model of tumor\u2013immune interactions\
  \ with chemotherapy, and strategiesfor optimally administering treatment. In this\
  \ paper we analyze the dynamics of this model, ch."
models:
- alias: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.state
  to:
  - visualisation.immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model_state
- from: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.summary
  to:
  - visualisation.immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model_summary
- from: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.species_labels
  to:
  - visualisation.immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `T`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `N`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `C`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.0
    units: native source value
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `M`.
  - name: removal_of_chemotherapeutic_drug_at_ther_target_site_rate
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.removal_of_chemotherapeutic_drug_at_ther_target_site_rate
    label: Removal Of Chemotherapeutic Drug At Ther Target Site Rate
    default: 0.9
    units: native source value
    description: Removal Of Chemotherapeutic Drug At Ther Target Site Rate. Sets bundled
      SBML parameter `gamma`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.state
  - name: summary
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.summary
  - name: species_labels
    maps_to: immunology_sbml_depillis2007_chemotherapy_for_tumors_an_analysis_model2001160001_model.species_labels
