schema_version: '2.0'
title: Eftimie2018 - Cancer and Immune biomarkers Lab
description: 'The paper describes a model on the detection of cancer based on cancer
  and immune biomarkers. Created by COPASI 4.25 (Build 207) This model is described
  in the article: Improving cancer detection thro.'
models:
- alias: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.state
  to:
  - visualisation.immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model_state
- from: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.summary
  to:
  - visualisation.immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model_summary
- from: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.species_labels
  to:
  - visualisation.immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `NT`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `NI`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `BT`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `BI`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.state
  - name: summary
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.summary
  - name: species_labels
    maps_to: immunology_sbml_eftimie2018_cancer_and_immune_biomarkers_biomd0000000741_model.species_labels
