schema_version: '2.0'
title: Isaeva2008 - Modelling of Anti-Tumour Immune Response Immunocorrective Effect
  of Weak Centimetre Electromagnetic Waves Lab
description: 'Modelling of anti-tumour immune response: Immunocorrective effectof
  weak centimetre electromagnetic wavesO.G. It can be used to explore immune response
  dynamics and compare pathway-level behavior across conditions.'
models:
- alias: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.state
  to:
  - visualisation.immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model_state
- from: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.summary
  to:
  - visualisation.immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model_summary
- from: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.species_labels
  to:
  - visualisation.immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 240000.0
    units: native source value
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `L`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 200000.0
    units: native source value
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `T`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 36000000.0
    units: native source value
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `I2`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.unresolved_tumor_observable_3
  - name: state
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.state
  - name: summary
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.summary
  - name: species_labels
    maps_to: immunology_sbml_isaeva2008_modelling_of_anti_tumour_immune_respo_biomd0000000910_model.species_labels
