schema_version: '2.0'
title: Saad2017 - immune checkpoint and BCG in superficial bladder cancer Lab
description: The paper describes a model on the Dynamics of Immune Checkpoints, Immune
  System, and BCG in the Treatment of Superficial Bladder Cancer. It can be used to
  explore immune response dynamics and compare pathway-level behavior across conditions.
models:
- alias: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.state
  to:
  - visualisation.immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model_state
- from: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.summary
  to:
  - visualisation.immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model_summary
- from: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.species_labels
  to:
  - visualisation.immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 100000.0
    units: substance
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `C`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `E`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `B`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.0
    units: substance
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `P`.
  - name: cancer_growth_rate
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.cancer_growth_rate
    label: Cancer Growth Rate
    default: 0.0033
    units: unit_0
    description: Cancer Growth Rate. Sets bundled SBML parameter `r`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.state
  - name: summary
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.summary
  - name: species_labels
    maps_to: immunology_sbml_saad2017_immune_checkpoint_and_bcg_in_superficia_biomd0000000746_model.species_labels
