schema_version: '2.0'
title: Mullinax2016 - Mathematical model of tumor-immune cell interactions to optimize
  the meta-phenotype of TIL subpopulations Lab
description: "This model is described in the publication:John Mullinax, Cliona O\u2019\
  Farrelly, Jacob G. It can be used to explore immune response dynamics and compare\
  \ pathway-level behavior across conditions."
models:
- alias: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.state
  to:
  - visualisation.immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model_state
- from: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.summary
  to:
  - visualisation.immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model_summary
- from: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.species_labels
  to:
  - visualisation.immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `T`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 0.1
    units: native source value
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `E`.
  - name: initial_unresolved_tumor_observable_3
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.initial_unresolved_tumor_observable_3
    label: Initial Unresolved Tumor Observable 3
    default: 0.1
    units: native source value
    description: Initial Unresolved Tumor Observable 3. Sets the initial value of
      bundled SBML species `N`.
  - name: initial_unresolved_tumor_observable_4
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.initial_unresolved_tumor_observable_4
    label: Initial Unresolved Tumor Observable 4
    default: 0.1
    units: native source value
    description: Initial Unresolved Tumor Observable 4. Sets the initial value of
      bundled SBML species `R`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.unresolved_tumor_observable_2
  - name: unresolved_tumor_observable_3
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.unresolved_tumor_observable_3
  - name: unresolved_tumor_observable_4
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.unresolved_tumor_observable_4
  - name: state
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.state
  - name: summary
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.summary
  - name: species_labels
    maps_to: immunology_sbml_mullinax2016_mathematical_model_of_tumor_immune_model2109110006_model.species_labels
