schema_version: '2.0'
title: Feizabadi2011/1 - immunodeficiency in cancer core model Lab
description: 'The paper describes a basic model of immune-cancer interaction. Created
  by COPASI 4.25 (Build 207) This model is described in the article: Modeling the
  Effects of a Simple Immune System and Immunodefi.'
models:
- alias: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.state
  to:
  - visualisation.immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model_state
- from: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.summary
  to:
  - visualisation.immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model_summary
- from: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.species_labels
  to:
  - visualisation.immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_tumor_observable_1
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.initial_unresolved_tumor_observable_1
    label: Initial Unresolved Tumor Observable 1
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 1. Sets the initial value of
      bundled SBML species `T`.
  - name: initial_unresolved_tumor_observable_2
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.initial_unresolved_tumor_observable_2
    label: Initial Unresolved Tumor Observable 2
    default: 1.0
    units: native source value
    description: Initial Unresolved Tumor Observable 2. Sets the initial value of
      bundled SBML species `N`.
  outputs:
  - name: unresolved_tumor_observable_1
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.unresolved_tumor_observable_1
  - name: unresolved_tumor_observable_2
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.unresolved_tumor_observable_2
  - name: state
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.state
  - name: summary
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.summary
  - name: species_labels
    maps_to: immunology_sbml_feizabadi2011_1_immunodeficiency_in_cancer_core_biomd0000000760_model.species_labels
