schema_version: '2.0'
title: Zhou2015 - Circadian clock with immune regulator NPR1 Lab
description: Zhou2015 - Circadian clock with immuneregulator NPR1 Arabidopsis clock
  model modified fromP2012 (Pokhilko et al., 2013 - BIOMD0000000445 )model to include
  the master immune regulator NPR1 coupling to. It can be used to explore immune response
  dynamics and compare pathway-level behavior across conditions.
models:
- alias: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.state
  to:
  - visualisation.immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model_state
- from: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.summary
  to:
  - visualisation.immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model_summary
- from: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.species_labels
  to:
  - visualisation.immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_cabar_m
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.initial_cabar_m
    label: Initial Cabar M
    default: 0.856
    units: native source value
    description: Initial Cabar M. Sets the initial value of bundled SBML species `species_1`.
  - name: initial_unresolved_source_observable_2
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.initial_unresolved_source_observable_2
    label: Initial Unresolved Source Observable 2
    default: 0.4027
    units: native source value
    description: Initial Unresolved Source Observable 2. Sets the initial value of
      bundled SBML species `species_2`.
  - name: initial_unresolved_source_observable_3
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.initial_unresolved_source_observable_3
    label: Initial Unresolved Source Observable 3
    default: 0.2362
    units: native source value
    description: Initial Unresolved Source Observable 3. Sets the initial value of
      bundled SBML species `species_3`.
  - name: initial_unresolved_source_observable_4
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.initial_unresolved_source_observable_4
    label: Initial Unresolved Source Observable 4
    default: 0.2843
    units: native source value
    description: Initial Unresolved Source Observable 4. Sets the initial value of
      bundled SBML species `species_4`.
  - name: initial_unresolved_signaling_observable_2
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.initial_unresolved_signaling_observable_2
    label: Initial Unresolved Signaling Observable 2
    default: 1.3143
    units: native source value
    description: Initial Unresolved Signaling Observable 2. Sets the initial value
      of bundled SBML species `cCOP1c`.
  outputs:
  - name: cabar_m
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.cabar_m
  - name: unresolved_source_observable_2
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.unresolved_source_observable_2
  - name: unresolved_source_observable_3
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.unresolved_source_observable_3
  - name: unresolved_source_observable_4
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.unresolved_source_observable_4
  - name: unresolved_signaling_observable_2
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.unresolved_signaling_observable_2
  - name: state
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.state
  - name: summary
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.summary
  - name: species_labels
    maps_to: immunology_sbml_zhou2015_circadian_clock_with_immune_regulator_n_biomd0000000577_model.species_labels
