schema_version: '2.0'
title: Coulibaly2019 - Interleukin-15 Signaling in HIF-1a Regulation in Natural Killer
  Cells Lab
description: This is a mathematical model comprised of non-linear ordinary differential
  equations describing the dynamic relationship between hypoxia-inducible factor-1
  alpha (HIF-1a) mRNA, HIF-1a protein, and int. It can be used to explore immune response
  dynamics and compare pathway-level behavior across conditions.
models:
- alias: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model
  path: models/core
- alias: visualisation
  path: models/visualisation
wiring:
- from: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.state
  to:
  - visualisation.immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model_state
- from: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.summary
  to:
  - visualisation.immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model_summary
- from: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.species_labels
  to:
  - visualisation.immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model_species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
io:
  inputs:
  - name: initial_unresolved_signaling_observable_1
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.initial_unresolved_signaling_observable_1
    label: Initial Unresolved Signaling Observable 1
    default: 1.0
    units: native source value
    description: Initial Unresolved Signaling Observable 1. Sets the initial value
      of bundled SBML species `y1_IL_15`.
  - name: initial_unresolved_signaling_observable_2
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.initial_unresolved_signaling_observable_2
    label: Initial Unresolved Signaling Observable 2
    default: 0.05
    units: native source value
    description: Initial Unresolved Signaling Observable 2. Sets the initial value
      of bundled SBML species `y4_HIF_1a`.
  - name: initial_unresolved_signaling_observable_3
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.initial_unresolved_signaling_observable_3
    label: Initial Unresolved Signaling Observable 3
    default: 1.0
    units: native source value
    description: Initial Unresolved Signaling Observable 3. Sets the initial value
      of bundled SBML species `y5_HIF_1b`.
  - name: initial_unresolved_signaling_observable_4
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.initial_unresolved_signaling_observable_4
    label: Initial Unresolved Signaling Observable 4
    default: 0.05
    units: native source value
    description: Initial Unresolved Signaling Observable 4. Sets the initial value
      of bundled SBML species `y6_HIF_1_Complex`.
  - name: initial_unresolved_signaling_observable_5
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.initial_unresolved_signaling_observable_5
    label: Initial Unresolved Signaling Observable 5
    default: 1.0
    units: native source value
    description: Initial Unresolved Signaling Observable 5. Sets the initial value
      of bundled SBML species `y7_NF_KB`.
  outputs:
  - name: unresolved_signaling_observable_1
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.unresolved_signaling_observable_1
  - name: unresolved_signaling_observable_2
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.unresolved_signaling_observable_2
  - name: unresolved_signaling_observable_3
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.unresolved_signaling_observable_3
  - name: unresolved_signaling_observable_4
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.unresolved_signaling_observable_4
  - name: unresolved_signaling_observable_5
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.unresolved_signaling_observable_5
  - name: state
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.state
  - name: summary
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.summary
  - name: species_labels
    maps_to: immunology_sbml_coulibaly2019_interleukin_15_signaling_in_hif_1a_biomd0000000867_model.species_labels
